insert into public.skill_catalog (area, nome, tipo, ensino_medio)
values
('Administrativo', 'Organização de documentos', 'funcao', true),
('Administrativo', 'Atendimento telefônico', 'funcao', true),
('Administrativo', 'Lançamento de informações em planilhas', 'funcao', true),
('Administrativo', 'Controle de arquivos', 'funcao', true),
('Administrativo', 'Apoio em rotinas administrativas', 'funcao', true),
('Administrativo', 'Conhecimento básico em informática', 'tecnica', true),
('Administrativo', 'Organização', 'comportamental', true),
('Administrativo', 'Atenção aos detalhes', 'comportamental', true),
('Atendimento ao cliente', 'Recepcionar clientes', 'funcao', true),
('Atendimento ao cliente', 'Orientar clientes', 'funcao', true),
('Atendimento ao cliente', 'Registrar solicitações', 'funcao', true),
('Atendimento ao cliente', 'Comunicação clara', 'comportamental', true),
('Atendimento ao cliente', 'Paciência', 'comportamental', true),
('Atendimento ao cliente', 'Educação no atendimento', 'comportamental', true),
('Vendas', 'Apoio na abordagem de clientes', 'funcao', true),
('Vendas', 'Organização de produtos', 'funcao', true),
('Vendas', 'Proatividade', 'comportamental', true),
('Vendas', 'Persuasão ética', 'comportamental', true),
('Operador de caixa', 'Apoio na organização do caixa', 'funcao', true),
('Operador de caixa', 'Conferência de valores sob supervisão', 'funcao', true),
('Operador de caixa', 'Noção básica de matemática', 'tecnica', true),
('Operador de caixa', 'Honestidade', 'comportamental', true),
('Estoque e reposição', 'Reposição de produtos', 'funcao', true),
('Estoque e reposição', 'Conferência de validade', 'funcao', true),
('Estoque e reposição', 'Apoio em inventário', 'funcao', true),
('Estoque e reposição', 'Agilidade', 'comportamental', true),
('Padaria / Mercado / Comércio', 'Atendimento no balcão', 'funcao', true),
('Padaria / Mercado / Comércio', 'Organização de prateleiras', 'funcao', true),
('Padaria / Mercado / Comércio', 'Higiene e cuidado', 'comportamental', true),
('Loja de roupas', 'Organização de araras', 'funcao', true),
('Loja de roupas', 'Apoio no provador', 'funcao', true),
('Loja de roupas', 'Boa apresentação', 'comportamental', true),
('Telemarketing / Comunicação', 'Contato com clientes', 'funcao', true),
('Telemarketing / Comunicação', 'Atualização de cadastro', 'funcao', true),
('Telemarketing / Comunicação', 'Dicção clara', 'comportamental', true),
('Tecnologia básica / Informática', 'Digitação', 'tecnica', true),
('Tecnologia básica / Informática', 'Uso de planilhas simples', 'tecnica', true),
('Tecnologia básica / Informática', 'Cadastro em sistemas', 'funcao', true),
('Tecnologia básica / Informática', 'Raciocínio lógico', 'comportamental', true)
on conflict (area, nome) do nothing;
